// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgbean.proto

#ifndef PROTOBUF_msgbean_2eproto__INCLUDED
#define PROTOBUF_msgbean_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace spplus {
namespace buff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msgbean_2eproto();
void protobuf_AssignDesc_msgbean_2eproto();
void protobuf_ShutdownFile_msgbean_2eproto();

class UserBean;

// ===================================================================

class UserBean : public ::google::protobuf::Message {
 public:
  UserBean();
  virtual ~UserBean();

  UserBean(const UserBean& from);

  inline UserBean& operator=(const UserBean& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserBean& default_instance();

  void Swap(UserBean* other);

  // implements Message ----------------------------------------------

  UserBean* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserBean& from);
  void MergeFrom(const UserBean& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes userid = 1;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUseridFieldNumber = 1;
  inline const ::std::string& userid() const;
  inline void set_userid(const ::std::string& value);
  inline void set_userid(const char* value);
  inline void set_userid(const void* value, size_t size);
  inline ::std::string* mutable_userid();
  inline ::std::string* release_userid();
  inline void set_allocated_userid(::std::string* userid);

  // optional bytes username = 2;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 2;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const void* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional bytes userrole = 3;
  inline bool has_userrole() const;
  inline void clear_userrole();
  static const int kUserroleFieldNumber = 3;
  inline const ::std::string& userrole() const;
  inline void set_userrole(const ::std::string& value);
  inline void set_userrole(const char* value);
  inline void set_userrole(const void* value, size_t size);
  inline ::std::string* mutable_userrole();
  inline ::std::string* release_userrole();
  inline void set_allocated_userrole(::std::string* userrole);

  // @@protoc_insertion_point(class_scope:com.spplus.buff.UserBean)
 private:
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_userrole();
  inline void clear_has_userrole();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* userid_;
  ::std::string* username_;
  ::std::string* userrole_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_msgbean_2eproto();
  friend void protobuf_AssignDesc_msgbean_2eproto();
  friend void protobuf_ShutdownFile_msgbean_2eproto();

  void InitAsDefaultInstance();
  static UserBean* default_instance_;
};
// ===================================================================


// ===================================================================

// UserBean

// optional bytes userid = 1;
inline bool UserBean::has_userid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserBean::set_has_userid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserBean::clear_has_userid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserBean::clear_userid() {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    userid_->clear();
  }
  clear_has_userid();
}
inline const ::std::string& UserBean::userid() const {
  return *userid_;
}
inline void UserBean::set_userid(const ::std::string& value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void UserBean::set_userid(const char* value) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(value);
}
inline void UserBean::set_userid(const void* value, size_t size) {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  userid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserBean::mutable_userid() {
  set_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    userid_ = new ::std::string;
  }
  return userid_;
}
inline ::std::string* UserBean::release_userid() {
  clear_has_userid();
  if (userid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = userid_;
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserBean::set_allocated_userid(::std::string* userid) {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    delete userid_;
  }
  if (userid) {
    set_has_userid();
    userid_ = userid;
  } else {
    clear_has_userid();
    userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes username = 2;
inline bool UserBean::has_username() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserBean::set_has_username() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserBean::clear_has_username() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserBean::clear_username() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& UserBean::username() const {
  return *username_;
}
inline void UserBean::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void UserBean::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void UserBean::set_username(const void* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserBean::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  return username_;
}
inline ::std::string* UserBean::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserBean::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes userrole = 3;
inline bool UserBean::has_userrole() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserBean::set_has_userrole() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserBean::clear_has_userrole() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserBean::clear_userrole() {
  if (userrole_ != &::google::protobuf::internal::kEmptyString) {
    userrole_->clear();
  }
  clear_has_userrole();
}
inline const ::std::string& UserBean::userrole() const {
  return *userrole_;
}
inline void UserBean::set_userrole(const ::std::string& value) {
  set_has_userrole();
  if (userrole_ == &::google::protobuf::internal::kEmptyString) {
    userrole_ = new ::std::string;
  }
  userrole_->assign(value);
}
inline void UserBean::set_userrole(const char* value) {
  set_has_userrole();
  if (userrole_ == &::google::protobuf::internal::kEmptyString) {
    userrole_ = new ::std::string;
  }
  userrole_->assign(value);
}
inline void UserBean::set_userrole(const void* value, size_t size) {
  set_has_userrole();
  if (userrole_ == &::google::protobuf::internal::kEmptyString) {
    userrole_ = new ::std::string;
  }
  userrole_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserBean::mutable_userrole() {
  set_has_userrole();
  if (userrole_ == &::google::protobuf::internal::kEmptyString) {
    userrole_ = new ::std::string;
  }
  return userrole_;
}
inline ::std::string* UserBean::release_userrole() {
  clear_has_userrole();
  if (userrole_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = userrole_;
    userrole_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserBean::set_allocated_userrole(::std::string* userrole) {
  if (userrole_ != &::google::protobuf::internal::kEmptyString) {
    delete userrole_;
  }
  if (userrole) {
    set_has_userrole();
    userrole_ = userrole;
  } else {
    clear_has_userrole();
    userrole_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace buff
}  // namespace spplus
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgbean_2eproto__INCLUDED
